name = "HailServerPack"
author = "Vlackdimir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dfc3db57c83b7255e77d88663293a19ae3099479946f2d754346746d5cab083"

[versions]
forge = "43.2.3"
minecraft = "1.19.2"
