name = "HailServerPack"
author = "Vlackdimir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a6472c54a70d773e2411196ac540e8c3daf1170a50c139f22a224bda2d26993"

[versions]
forge = "43.2.3"
minecraft = "1.19.2"
