name = "HailServerPack"
author = "Vlackdimir"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8980f9bc6563bf6f10e57bd40230e3c0957ca4fb843fa8f7dd460fb3be98c98f"

[versions]
forge = "43.2.3"
minecraft = "1.19.2"
